In [24]:
import sys
import numpy as np
import ase.io.vasp
import ase.io.lammpsdata
from ase import Atoms
from ase.visualize import view
from ase import build

In [25]:
#Reads structure from .cif file and creates Atoms object
struc_input = ase.io.vasp.read_vasp('POSCAR.vasp')
view(struc_input)

<Popen: returncode: None args: ['/home/ubc_oadicks/anaconda3/envs/acesuit/bi...>

In [31]:
trans_mat = np.zeros((3,3))
print(trans_mat)
trans_mat[0][0] = 5
trans_mat[1][1] = 5
trans_mat[2][2] = 5
print(trans_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [32]:
struc_scell = ase.build.make_supercell(struc_input,trans_mat)
view(struc_scell)

<Popen: returncode: None args: ['/home/ubc_oadicks/anaconda3/envs/acesuit/bi...>

In [33]:
ase.io.lammpsdata.write_lammps_data("data.structure",atoms=struc_scell,units="metal",atom_style="charge")